# Paths are relative to this archive, independent of the caller's working directory.
.script <- sub('^--file=', '', commandArgs(FALSE)[grepl('^--file=', commandArgs(FALSE))])
root <- normalizePath(file.path(dirname(.script), '..'))
setwd(root)
library(ggplot2)
library(readr)
library(tidyr)
library(dplyr)
setwd('data/structure/admixture')
samplelist <- read_tsv("../sample_order.txt",
                       col_names = "sample")

all_data <- tibble(sample=character(),
                   k=numeric(),
                   Q=character(),
                   value=numeric())
for (k in 2:8){
  data <- read_delim(paste0("257.snps.hardfiltered.maf01ms90thin1k.",k,".Q"),
                     col_names = paste0("Q",seq(1:k)),
                     delim=" ")
  data$sample <- samplelist$sample
  data$k <- k
  data %>% gather(Q, value, -sample,-k) -> data
  all_data <- rbind(all_data,data)
}
all_data$sample = factor(all_data$sample,levels=c("XubBo-1037-1A",
                                                  "XubBo-1037-2A",
                                                  "XubBo-1037-3A",
                                                  "XubBo-1037-4A",
                                                  "XubBo-1037-5A",
                                                  "XubBo-1037-6A",
                                                  "XubBo-1037-7A",
                                                  "XubBo-1037-8A",
                                                  "xubo266-2A",
                                                  "xubo266-3A",
                                                  "xubo266-4A",
                                                  "xubo266-5A",
                                                  "xubo266-6A",
                                                  "xubo266-8A",
                                                  "xubo266-9A",
                                                  "ZXL79-1A",
                                                  "ZXL79-2A",
                                                  "ZXL79-3A",
                                                  "ZXL79-4A",
                                                  "ZXL79-5A",
                                                  "ZXL79-6A",
                                                  "ZXL79-7A",
                                                  "ZXL79-18A",
                                                  "DP1709141A",
                                                  "DP1709142A",
                                                  "DP1709143A",
                                                  "DP1709144A",
                                                  "DP1709145A",
                                                  "DP1709146A",
                                                  "DP1709147A",
                                                  "DP1709148A",
                                                  "XubBo1030-10A",
                                                  "XubBo1030-1A",
                                                  "XubBo1030-3A",
                                                  "XubBo1030-4A",
                                                  "XubBo1030-5A",
                                                  "XubBo1030-6A",
                                                  "XubBo1030-8A",
                                                  "XubBo1030-9A",
                                                  "ZXL277-1A",
                                                  "ZXL277-2A",
                                                  "ZXL277-3A",
                                                  "ZXL277-4A",
                                                  "ZXL277-5A",
                                                  "ZXL277-6A",
                                                  "ZXL277-7A",
                                                  "ZXL277-8A",
                                                  "XuBo982-1A",
                                                  "XuBo982-2A",
                                                  "XuBo982-3A",
                                                  "XuBo982-4A",
                                                  "XuBo982-5A",
                                                  "XuBo982-6A",
                                                  "XuBo982-7A",
                                                  "XuBo982-8A",
                                                  "XubBo1051-10A",
                                                  "XubBo1051-1A",
                                                  "XubBo1051-2A",
                                                  "XubBo1051-3A",
                                                  "XubBo1051-4A",
                                                  "XubBo1051-7A",
                                                  "XubBo1051-8A",
                                                  "XubBo1051-9A",
                                                  "XuBo-97-11B",
                                                  "XuBo-97-2B",
                                                  "XuBo-97-3B",
                                                  "XuBo-97-4B",
                                                  "XuBo-97-5B",
                                                  "XuBo-97-7B",
                                                  "XuBo-97-8A",
                                                  "XuBo-97-9B",
                                                  "Sha-WS-1A",
                                                  "Sha-WS-2A",
                                                  "Sha-WS-3A",
                                                  "Sha-WS-4A",
                                                  "Sha-WS-5A",
                                                  "Sha-WS-6A",
                                                  "Sha-WS-7A",
                                                  "Sha-WS-8A",
                                                  "xubo01410-1A",
                                                  "xubo01410-2A",
                                                  "xubo01410-3A",
                                                  "xubo01410-4A",
                                                  "xubo01410-5A",
                                                  "xubo01410-6A",
                                                  "xubo01410-7A",
                                                  "xubo01410-8A",
                                                  "XB2014-144-2A",
                                                  "XB2014-144-3A",
                                                  "XB2014-144-4A",
                                                  "XB2014-144-5A",
                                                  "XB2014-144-6A",
                                                  "XB2014-144-7A",
                                                  "XB2014-144-8A",
                                                  "XB2014-144-9A",
                                                  "Gln2014-15-10A",
                                                  "Gln2014-15-1A",
                                                  "Gln2014-15-3A",
                                                  "Gln2014-15-4A",
                                                  "Gln2014-15-5A",
                                                  "Gln2014-15-6A",
                                                  "Gln2014-15-7A",
                                                  "Gln2014-15-8A",
                                                  "YLZB4703-2A",
                                                  "YLZB4703-3A",
                                                  "YLZB4703-4A",
                                                  "YLZB4703-5A",
                                                  "YLZB4703-6A",
                                                  "YLZB4703-7A",
                                                  "YLZB4703-8A",
                                                  "YLZB4703-9A",
                                                  "JLS-BM001-1A",
                                                  "JLS-BM001-2A",
                                                  "JLS-BM001-3A",
                                                  "JLS-BM001-4A",
                                                  "JLS-BM001-5A",
                                                  "JLS-BM001-6A",
                                                  "JLS-BM001-7A",
                                                  "JLS-BM001-8A",
                                                  "XB2014-4-2A",
                                                  "XB2014-4-3A",
                                                  "XB2014-4-4A",
                                                  "XB2014-4-5A",
                                                  "XB2014-4-6A",
                                                  "XB2014-4-7A",
                                                  "XB2014-4-8A",
                                                  "XB2014-4-9A",
                                                  "XubBo2014-131-1A",
                                                  "XubBo2014-131-2A",
                                                  "XubBo2014-131-3A",
                                                  "XubBo2014-131-4A",
                                                  "XubBo2014-131-5A",
                                                  "XubBo2014-131-6A",
                                                  "XubBo2014-131-7A",
                                                  "XubBo2014-131-8A",
                                                  "YLZB4715-10A",
                                                  "YLZB4715-1A",
                                                  "YLZB4715-2A",
                                                  "YLZB4715-5A",
                                                  "YLZB4715-6A",
                                                  "YLZB4715-7A",
                                                  "YLZB4715-8A",
                                                  "YLZB4715-9A",
                                                  "XB2014-48-1A",
                                                  "XB2014-48-2A",
                                                  "XB2014-48-3A",
                                                  "XB2014-48-4A",
                                                  "XB2014-48-5A",
                                                  "XB2014-48-6A",
                                                  "XB2014-48-7A",
                                                  "XB2014-48-9A",
                                                  "XB2014-38-2A",
                                                  "XB2014-38-3A",
                                                  "XB2014-38-4A",
                                                  "XB2014-38-6A",
                                                  "Xubo01402-2A",
                                                  "Xubo01402-3A",
                                                  "Xubo01402-4A",
                                                  "Xubo01402-5A",
                                                  "Xubo01402-6A",
                                                  "Xubo01402-7A",
                                                  "Xubo01402-8A",
                                                  "Xubo01402-9A",
                                                  "2014-3-10A",
                                                  "2014-3-3A",
                                                  "2014-3-4A",
                                                  "2014-3-5A",
                                                  "2014-3-6A",
                                                  "2014-3-7A",
                                                  "2014-3-8A",
                                                  "2014-3-9A",
                                                  "THP-SET_1917-1A",
                                                  "THP-SET_1917-2A",
                                                  "THP-SET_1917-3A",
                                                  "THP-SET_1917-4A",
                                                  "THP-SET_1917-5A",
                                                  "THP-SET_1917-6A",
                                                  "THP-SET_1917-7A",
                                                  "THP-SET_1917-8A",
                                                  "JLS-CY022-10A",
                                                  "JLS-CY022-11A",
                                                  "JLS-CY022-12A",
                                                  "JLS-CY022-13A",
                                                  "JLS-CY022-4A",
                                                  "JLS-CY022-5A",
                                                  "JLS-CY022-6A",
                                                  "JLS-CY022-7A",
                                                  "2014-132-2A",
                                                  "2014-132-3A",
                                                  "2014-132-4A",
                                                  "2014-132-5A",
                                                  "2014-132-6A",
                                                  "2014-132-7A",
                                                  "2014-132-8A",
                                                  "2014-132-9A",
                                                  "2014-128-1A",
                                                  "2014-128-2A",
                                                  "2014-128-3A",
                                                  "2014-128-4A",
                                                  "2014-128-5A",
                                                  "2014-128-6A",
                                                  "2014-128-8A",
                                                  "2014-66-1A",
                                                  "2014-66-2A",
                                                  "2014-66-3A",
                                                  "2014-66-4A",
                                                  "2014-66-5A",
                                                  "2014-66-6A",
                                                  "2014-66-7A",
                                                  "2014-66-8A",
                                                  "Gln2014-8-1A",
                                                  "Gln2014-8-2A",
                                                  "Gln2014-8-4A",
                                                  "Gln2014-8-5A",
                                                  "Gln2014-8-6A",
                                                  "Gln2014-8-7A",
                                                  "Gln2014-8-8A",
                                                  "XB2014-39-1A",
                                                  "XB2014-39-2A",
                                                  "XB2014-39-3A",
                                                  "XB2014-39-4A",
                                                  "XB2014-39-5A",
                                                  "XB2014-39-6A",
                                                  "XB2014-39-7A",
                                                  "XB2014-39-8A",
                                                  "XB2014-38-5A",
                                                  "XB26-11B",
                                                  "XB26-12B",
                                                  "XB26-13B",
                                                  "XB26-3B",
                                                  "XB26-4B",
                                                  "XB26-5B",
                                                  "XB26-7B",
                                                  "YLZB4816-11A",
                                                  "YLZB4816-3A",
                                                  "YLZB4816-4A",
                                                  "YLZB4816-5A",
                                                  "YLZB4816-6A",
                                                  "YLZB4816-7A",
                                                  "YLZB4816-8A",
                                                  "YLZB4816-9A",
                                                  "zhuzm1009-10A",
                                                  "zhuzm1009-1A",
                                                  "zhuzm1009-2A",
                                                  "zhuzm1009-3A",
                                                  "zhuzm1009-4A",
                                                  "zhuzm1009-6A",
                                                  "zhuzm1009-7A",
                                                  "zhuzm1009-8A",
                                                  "YLZB4735-10A",
                                                  "YLZB4735-1A",
                                                  "YLZB4735-2A",
                                                  "YLZB4735-3A",
                                                  "YLZB4735-5A",
                                                  "YLZB4735-6A",
                                                  "YLZB4735-8A",
                                                  "YLZB4735-9A"))


p <- all_data %>%
  ggplot(.,aes(x=sample,y=value,fill=factor(Q))) + 
  geom_bar(stat="identity",position="stack") +
  xlab("Sample") + ylab("Ancestry") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1,size = 3)) +
  scale_fill_brewer(palette="Set2",name="K",
                    labels=seq(1:8)) +
  facet_wrap(~k,ncol=1 )


dir.create(file.path(root,'results/structure'),recursive=TRUE,showWarnings=FALSE)
ggsave(file.path(root,'results/structure/maf01ms09_re.pdf'),p,width = 15, height = 9)
